#     # ######
##   ## #     #
# # # # #     #
#  #  # ######
#     # #   #
#     # #    #
#     # #     # Melhem Rizk

format = """
$username\
$os\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$conda\
$time\
$cmd_duration
âœ (fg:#ffffff)
"""

# Enable the blank line at the start of the prompt
add_newline = true

# Displays your user name
[username]
show_always = true
style_user = "fg:#ff5500"
style_root = "fg:#ff0000"
format = '[$user ]($style bold)'
disabled = false

# Displays a symbol of your operating system. You can select which symbol to display in the [os.symbols] module
[os]
style = "fg:#145a32"
format = ' using [$symbol]($style bold)'
disabled = false # Disabled by default

[os.symbols]
openSUSE = "ğŸ¦"

# Dispalys the hostname
[hostname]
ssh_only = false
style = "fg:#1e8449"
format = ' at [$hostname]($style bold)'
disabled = false

# Displays the your current working directory
[directory]
read_only = 'ğŸ”’'
style = "fg:#9b59b6"
read_only_style = "fg:#ff0000"
format = " in [ $path ]($style bold italic)[$read_only]($read_only_style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Replace some directories with icons, to shorten the path
#[directory.substitutions]
#"Documents" = "ó°ˆ™ "
#"Downloads" = "ï€™ "
#"Music" = "ï€ "
#"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

# Displays the time it takes to execute a command
[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "fg:#de3163 bold italic"


[python]
symbol = "ğŸ "
#pyenv_version_name = true
format = ' via [${symbol}python (${version} )(\($virtualenv\) )]($style bold)'
style = "fg:#7d3c98"
#pyenv_prefix = "venv "
#python_binary = ["./venv/bin/python", "python", "python3", "python2"]
#detect_extensions = ["py"]
#version_format = "v${raw}"


[conda]
symbol = "ï„Œ "
style = "fg:#7d3c98"
format = ' via [$symbol$environment]($style bold)'
disabled = false

[git_branch]
symbol = "ï˜"
style = "fg:#2e86c1"
format = ' on [ $symbol $branch ]($style)'

[git_status]
style = "fg:#21618c"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "fg:#7d3c98"
format = '[ $symbol ($version) ]($style)'


[nodejs]
symbol = "îœ˜"
style = "fg:#7d3c98"
format = '[ $symbol ($version) ]($style)'

# Displays the time in 24hr format
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#00aaff"
format = '[ â™¥ $time ]($style bold)'



