
# Options

add_newline = true


format = """
[î‚¶](#d35400)\
$username\
$os\
[î‚°](fg:#ff5500 bg:#1e8449)\
$hostname\
[î‚°](fg:#1e8449 bg:#9b59b6)\
$directory\
[î‚°](fg:#9b59b6 bg:#21618c)\
$git_branch\
$git_status\
[î‚°](fg:#21618c bg:#7d3c98)\
$python\
$conda\
[î‚°](fg:#7d3c98 bg:#00aaff)\
$time\
[î‚° ](fg:#00aaff)
âœ (fg:#ffffff)
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#ff5500 fg:#ffffff"
style_root = "bg:#ff0000 fg:#ffffff"
format = '[$user ]($style bold)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#ff5500 fg:#145a32"
disabled = false # Disabled by default

[hostname]
ssh_only = false
style = "bg:#1e8449 fg:#ffffff"
format = '[$hostname]($style bold)'
disabled = false

[directory]
read_only = ' ğŸ”’'
style = "bg:#9b59b6 fg:#ffffff"
format = "[ $path ]($style bold italic)"
truncation_length = 3
truncation_symbol = "â€¦/"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "fg:#de3163 bold italic"

[python]
symbol = "ğŸ "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style bold)'
style = "fg:#ffffff"
#pyenv_prefix = "venv "
#python_binary = ["./venv/bin/python", "python", "python3", "python2"]
#detect_extensions = ["py"]
#version_format = "v${raw}"


[conda]
style = "fg:#ffffff bg:#7d3c98"
format = '[$symbol$environment]($style bold)'
disabled = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
#[directory.substitutions]
#"Documents" = "ó°ˆ™ "
#"Downloads" = "ï€™ "
#"Music" = "ï€ "
#"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

[git_branch]
symbol = "ï˜"
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'


[nodejs]
symbol = "îœ˜"
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'


[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#00aaff fg:#ffffff"
format = '[ â™¥ $time ]($style bold)'



